### ISSUE TITLE
Register Form bug

### ISSUE THREAD

**Issue by pantsi98** [PanChee00/Adopse_Events_19_20#18]
Στo register form του χρήστη, εμφανίζει την επιβεβαίωση κωδικού ως απλά ψηφία και όχι στη μορφή password, δηλαδή με *******.
Επίσης υπάρχει ένα label το οποίο εμφανίζει τα τυχόν λάθη, αλλά σε περίπτωση που δεν υπάρχει λάθος, εμφανίζει την date of birth

**Comment by jbalashi** [comment]
Όλα τα παραπάνω έχουν λυθεί.
