### ISSUE TITLE
Event.cs missing variable

### ISSUE THREAD

**Issue by pantsi98** [PanChee00/Adopse_Events_19_20#39]
Στην κλάση Event (αρχείο event.cs) δεν πρέπει να υπάρχει η μεταβλητή participants_amount; Έχει παραληφθεί εσκεμένα ή απλώς δεν προστέθηκε καταλάθος;

**Comment by jbalashi** [comment]
Το variable δεν υπαρχει διοτι εχει διαγραφει απο την βαση . Εχει προσθεθει στο τραπεζι play καθως μετραμε συμμετεχοντες ανα παρασταση  και οχι ανα event (μέσω event_id στο play μπρουν να μετρηθουν οι συμμετεχοντες ανα event)
